// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomNumberComparator.proto

package com.pateo.hbase.defined.comparator;

public final class MyComparatorProtos {
  private MyComparatorProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CustomNumberComparatorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes value = 1;
    /**
     * <code>required bytes value = 1;</code>
     */
    boolean hasValue();
    /**
     * <code>required bytes value = 1;</code>
     */
    com.google.protobuf.ByteString getValue();

    // required string fieldType = 2;
    /**
     * <code>required string fieldType = 2;</code>
     */
    boolean hasFieldType();
    /**
     * <code>required string fieldType = 2;</code>
     */
    java.lang.String getFieldType();
    /**
     * <code>required string fieldType = 2;</code>
     */
    com.google.protobuf.ByteString
        getFieldTypeBytes();
  }
  /**
   * Protobuf type {@code CustomNumberComparator}
   */
  public static final class CustomNumberComparator extends
      com.google.protobuf.GeneratedMessage
      implements CustomNumberComparatorOrBuilder {
    // Use CustomNumberComparator.newBuilder() to construct.
    private CustomNumberComparator(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CustomNumberComparator(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CustomNumberComparator defaultInstance;
    public static CustomNumberComparator getDefaultInstance() {
      return defaultInstance;
    }

    public CustomNumberComparator getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CustomNumberComparator(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              value_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              fieldType_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pateo.hbase.defined.comparator.MyComparatorProtos.internal_static_CustomNumberComparator_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pateo.hbase.defined.comparator.MyComparatorProtos.internal_static_CustomNumberComparator_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator.class, com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator.Builder.class);
    }

    public static com.google.protobuf.Parser<CustomNumberComparator> PARSER =
        new com.google.protobuf.AbstractParser<CustomNumberComparator>() {
      public CustomNumberComparator parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomNumberComparator(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CustomNumberComparator> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>required bytes value = 1;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes value = 1;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    // required string fieldType = 2;
    public static final int FIELDTYPE_FIELD_NUMBER = 2;
    private java.lang.Object fieldType_;
    /**
     * <code>required string fieldType = 2;</code>
     */
    public boolean hasFieldType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string fieldType = 2;</code>
     */
    public java.lang.String getFieldType() {
      java.lang.Object ref = fieldType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fieldType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fieldType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFieldTypeBytes() {
      java.lang.Object ref = fieldType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fieldType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      value_ = com.google.protobuf.ByteString.EMPTY;
      fieldType_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFieldType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, value_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFieldTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, value_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFieldTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator)) {
        return super.equals(obj);
      }
      com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator other = (com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator) obj;

      boolean result = true;
      result = result && (hasValue() == other.hasValue());
      if (hasValue()) {
        result = result && getValue()
            .equals(other.getValue());
      }
      result = result && (hasFieldType() == other.hasFieldType());
      if (hasFieldType()) {
        result = result && getFieldType()
            .equals(other.getFieldType());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      if (hasFieldType()) {
        hash = (37 * hash) + FIELDTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getFieldType().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CustomNumberComparator}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparatorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pateo.hbase.defined.comparator.MyComparatorProtos.internal_static_CustomNumberComparator_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pateo.hbase.defined.comparator.MyComparatorProtos.internal_static_CustomNumberComparator_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator.class, com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator.Builder.class);
      }

      // Construct using com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        fieldType_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pateo.hbase.defined.comparator.MyComparatorProtos.internal_static_CustomNumberComparator_descriptor;
      }

      public com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator getDefaultInstanceForType() {
        return com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator.getDefaultInstance();
      }

      public com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator build() {
        com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator buildPartial() {
        com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator result = new com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fieldType_ = fieldType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator) {
          return mergeFrom((com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator other) {
        if (other == com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasFieldType()) {
          bitField0_ |= 0x00000002;
          fieldType_ = other.fieldType_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasValue()) {
          
          return false;
        }
        if (!hasFieldType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pateo.hbase.defined.comparator.MyComparatorProtos.CustomNumberComparator) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes value = 1;
      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes value = 1;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes value = 1;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>required bytes value = 1;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes value = 1;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      // required string fieldType = 2;
      private java.lang.Object fieldType_ = "";
      /**
       * <code>required string fieldType = 2;</code>
       */
      public boolean hasFieldType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string fieldType = 2;</code>
       */
      public java.lang.String getFieldType() {
        java.lang.Object ref = fieldType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fieldType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fieldType = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFieldTypeBytes() {
        java.lang.Object ref = fieldType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fieldType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fieldType = 2;</code>
       */
      public Builder setFieldType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fieldType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fieldType = 2;</code>
       */
      public Builder clearFieldType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fieldType_ = getDefaultInstance().getFieldType();
        onChanged();
        return this;
      }
      /**
       * <code>required string fieldType = 2;</code>
       */
      public Builder setFieldTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fieldType_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CustomNumberComparator)
    }

    static {
      defaultInstance = new CustomNumberComparator(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CustomNumberComparator)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomNumberComparator_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CustomNumberComparator_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034CustomNumberComparator.proto\":\n\026Custom" +
      "NumberComparator\022\r\n\005value\030\001 \002(\014\022\021\n\tfield" +
      "Type\030\002 \002(\tB@\n\"com.pateo.hbase.defined.co" +
      "mparatorB\022MyComparatorProtosH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CustomNumberComparator_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CustomNumberComparator_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CustomNumberComparator_descriptor,
              new java.lang.String[] { "Value", "FieldType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
